# agent states
FORWARD_TRANSLATION = 1
DODGING_OBSTACLE = 2
HALTING = 3
SEARCHING_FOR_HOLE = 4
FORWARD_TRANSLATION_AVOIDING = 5
APPROACHING_TARGET = 6
APPROACHED_TARGET = 7

# common velocity for all agents
NOMINAL_TITTER = 90 # degrees
NOMINAL_VELOCITY = 0.16 # m/s
MAXIMUM_VELOCITY = 0.35 # m/s

# distress types
DISTRESS_OBSTACLE_FOUND_SAFETY = 100
DISTRESS_OBSTACLE_NOT_FOUND_SAFETY = 200
DISTRESS_NONE = 300
DISTRESS_SLOW_DOWN_IN_PATH_OBSTACLES = 400

# safety not found search directions
SEARCH_DIRECTION_LEFT = 1000
SEARCH_DIRECTION_RIGHT = 2000


# agent safety data
SAFETY_RADIUS = 0.8 # metres
AGENT_RADIUS = 0.5 # metres
OBSTACLE_ALLOWANCE = 0.6 # metres

# translaion
TRANSLATION_INTERVAL = 1.0 # seconds

# sensing
OBSTACLE_PANIC_ACT_DISTANCE = AGENT_RADIUS + OBSTACLE_ALLOWANCE + 3.5 # metres # distance between agent and obstacle that will trigger distress
